version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_habi
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: habi
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password 
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - habi_network

networks:
  habi_network:
    driver: bridge